### PR TITLE
Fix plugin reading middle dependencies

### LINKED ISSUE #2: Position in dependency list is only responding to the last one
When you require in a define array, the plugin currently only recognizes the last element.\

e.g. ['A', 'B', 'C!largs'] will work but ['A', 'B!largs', 'C'] does not.

We should check for all cases.

### PR DESCRIPTION
**Pull request by rogeriochaves**
This fixes #2, it also fixes an issue where repeated plugins were getting loaded twice.

### CODE REVIEW

**Review by pamo — APPROVED** [review]
LGTM

File: src/plugin.js [hunk 1]
```diff
@@ -1,6 +1,7 @@
 'use strict';
 let ReplaceSource = require('webpack-sources').ReplaceSource;
 let RawSource = require('webpack-sources').RawSource;
+let uniq = require('ramda').uniq;
```
Comment (rogeriochaves) [inline src/plugin.js:4]: I've tried [ES6 Set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set), [uniq](https://www.npmjs.com/package/uniq), [array-uniq](https://www.npmjs.com/package/array-uniq) and [lodash.uniq](https://www.npmjs.com/package/lodash.uniq), none work for array of objects, ramda is the one true way.

Comment (pamo) [reply src/plugin.js:4]: Nice, I was going to ask about this. Thanks for clearing that up
